name: fmanager
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  get: ^4.6.6
  get_storage: ^2.1.1
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  google_sign_in: ^6.1.5
  dio: ^5.3.3
  flutter_screenutil: ^5.9.0
  logger: ^2.0.2+1
  dartz: ^0.10.1
  cached_network_image: ^3.3.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  path_provider: ^2.1.1
  http: ^1.1.0
  timelines: ^0.1.0
  lottie: ^2.7.0
  local_auth: ^2.1.7
  local_auth_android: ^1.0.34
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_typeahead: ^4.8.0
  image_picker: ^1.0.4
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/bottom/
    - assets/icons/teacher/
    - assets/images/
    - assets/anim/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_regular.ttf
        - asset: assets/fonts/poppins_bold.ttf
        - asset: assets/fonts/poppins_semibold.ttf
