// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa4LuntXQFF_Lncg4QYtsnf-RHXHe5dEw',
    appId: '1:18723735524:web:640932aedfcb5018ce69f1',
    messagingSenderId: '18723735524',
    projectId: 'fmanager-795a5',
    authDomain: 'fmanager-795a5.firebaseapp.com',
    storageBucket: 'fmanager-795a5.appspot.com',
    measurementId: 'G-5VRL1RF1ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeEj3qLZ7Nb8ZtQskFvpnEMcnGt2N2f98',
    appId: '1:18723735524:android:cf24e6386311de32ce69f1',
    messagingSenderId: '18723735524',
    projectId: 'fmanager-795a5',
    storageBucket: 'fmanager-795a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_zd_BujS6Z0pk0602BLqraWU15oSm6P0',
    appId: '1:18723735524:ios:2beb4113d7657c04ce69f1',
    messagingSenderId: '18723735524',
    projectId: 'fmanager-795a5',
    storageBucket: 'fmanager-795a5.appspot.com',
    iosBundleId: 'com.example.fmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_zd_BujS6Z0pk0602BLqraWU15oSm6P0',
    appId: '1:18723735524:ios:c3ce06150f613f4ace69f1',
    messagingSenderId: '18723735524',
    projectId: 'fmanager-795a5',
    storageBucket: 'fmanager-795a5.appspot.com',
    iosBundleId: 'com.example.fmanager.RunnerTests',
  );
}
